config/routes.rb
Rails.application.routes.draw do

  root "movies#index"

  get "movies" => "movies#index"
  get "movies/:id" => "movies#show", as: "movie"
  get "movies/:id/edit" => "movies#edit", as: "edit_movie"

  patch "movies/:id" => "movies#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  def flop?
    total_gross < 225_000_000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    movie_params =
      params.require(:movie).
        permit(:title, :description, :rating, :total_gross, :released_on)
    @movie.update(movie_params)
    redirect_to movies_path(@movies)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def release_date(movie)
    movie.released_on.strftime('%Y %B %d')
  end

  def total_gross(movie)
    if movie.flop?
      'Flop!'
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to image_tag("logo"), root_path %>
        <ul>
          <%= link_to "All movies", movies_path %>
        </ul>
      </nav>
    </header>

    <div class="content">
      <%= yield %>
    </div>

    <footer>
      <p>Made by Iryn Loza</p>
    </footer>
  </body>
</html>

app/views/movies/edit.html.erb
<h1> Editing <%= @movie.title %> </h1>

<%= form_with(model: @movie, local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :description %>
    <%= form.text_area :description, rows: 5 %>

    <%= form.label :rating %>
    <%= form.text_field :rating %>

    <%= form.label :total_gross %>
    <%= form.text_field :total_gross %>

    <%= form.label :released_on %>
    <%= form.date_select :released_on, {class: "date"} %>

    <%= form.submit %>
<% end %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
    <section class="movie">
        <div class="summary">
            <h2><%= link_to movie.title, movie %></h2>
            <h3> <%= release_date(movie) %> (<%= movie.rating %>) </h3>
            <span>
                <%= total_gross(movie) %>
            </span>
            <p>
                <%= truncate(movie.description, length: 35, separator: ' ') %>
            </p>
        </div>
    </section>
<% end %>       

app/views/movies/show.html.erb
<section class="movie-details">
    <div class="details">
        <h2><%= @movie.title %></h2>
        <h3> <%= release_date(@movie) %> (<%= @movie.rating %>) </h3>
        <span>
            <%= total_gross(@movie) %>
        </span>
        <p>
            <%= @movie.description %>
        </p>
    </div>
</section>

<section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
</section>